# Generated by Django 5.0.6 on 2024-06-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academido', '0003_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='turno',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
