# Generated by Django 5.0.6 on 2024-06-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academido', '0004_curso_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='turno',
        ),
    ]
